Triton and SmartOS documentation annotations
============================================

A collection of gotchas/links/workarounds/common pitfalls/howtos gleaned whilst
learning how to run Triton and migrate VMs to it. This is absolutely not a
tutorial and assumes a basic working knowledge of Triton SDC and SmartOS.
Also started life as a testbed for learning AsciiDoc works.


= The canonical documentation

The SmartOS docs are somewhat better than the Triton docs, the latter suffering
a bit from being out-of-date/incomplete. SmartOS docs are open, Triton currently
https://smartdatacenter.topicbox.com/groups/sdc-discuss/T9e09dbcc6e7f8847-M8692907c9d10fb8a7ec3243e/source-for-docs-at-docs-tritondatacenter-com[
are not].

* https://docs.tritondatacenter.com/public-cloud[End User documentation (i.e.
consumer docs)]
* https://docs.tritondatacenter.com/private-cloud[Operator documentation (i.e.
how to run the thing yourself)]
* https://docs.smartos.org[SmartOS official documentation]

= Other useful resources

* https://smartdatacenter.topicbox.com/groups/sdc-discuss/[Triton Data Center Topicbox mailing list]
* https://smartos.topicbox.com/groups/smartos-discuss/[SmartOS Topicbox mailing list]
* https://illumos.topicbox.com/groups/discuss/[Illumos discussion Topicbox mailing list]
* https://macktronics.com/tritoninst.html[This is a fabulously informative post]
that for me was instructional when initially prototyping Triton.
* https://www.davepacheco.net/blog/2024/illumos-physical-memory/[very deep dive
into illumos memory management]. Part two https://www.davepacheco.net/blog/2024/illumos-swap/[here].

= Hardware Virtual Machines

SmartOS supports both KVM and bhyve as VMMs. Only bhyve supports flexible disk
storage and instance resizing, making it the preferred choice.

== Building Bhyve images

* note how passing cdroms is different in bhyve as compared to KVM and how the
documentation is wrong: this link: https://smartos.topicbox.com/groups/smartos-discuss/T1d477bd26c796cad-M6ca9c8317093ee17879656c3

=== Triton Cloud Images

MNX maintain Triton images of Alma, Debian, Rocky and Ubuntu and these can be
imported from the public cloud (images.smartos.org) directly in the console. If
you wish to build your own the packer configuration, scripts etc. https://github.com/TritonDataCenter/triton-cloud-images[can be found here].

=== Creating a disk image (_not_ from an ISO)

Example VM image creation from an existing disk image (e.g. lift-and-shift of an
existing VM or an appliance-like image as in this example. This is based on https://docs.tritondatacenter.com/private-cloud/images/kvm[
the official documentation] with tweaks/fixes accommodating bhyve and a raw
image.

. On the headnode create a working directory in `/var/tmp`:
+
----
[root@headnode (cabin) /var/tmp]# mkdir talos-1.9.1
[root@headnode (cabin) /var/tmp]# cd talos-1.9.1/

----
. Fetch and decompress the image:
+
----
[root@headnode (cabin) /var/tmp/talos-1.9.1]# wget https://github.com/siderolabs/talos/releases/download/v1.9.1/metal-amd64.raw.zst
[root@headnode (cabin) /var/tmp/talos-1.9.1]# zstd -d metal-amd64.raw.zst
metal-amd64.raw.zst : 1306525696 bytes
----

. Create an instance definition:
+
----
[root@headnode (cabin) /var/tmp/talos-1.9.1]# cat 1.9.1.vmdef.json
{
  "name": "1.9.1",
  "brand": "bhyve",
  "vcpus": 1,
  "autoboot": false,
  "ram": 1024,
  "quota": 20,
  "bootrom": "/usr/share/bhyve/uefi-rom.bin",
  "disks": [
    {
      "boot": true,
      "model": "virtio",
      "size": 10240
    }
  ],
  "nics": [
    {
      "nic_tag": "external",
      "ip": "dhcp",
      "primary": "true",
      "model": "virtio"
    }
  ]
}
----

. Create an empty instance from the definition:
+
----
[root@headnode (cabin) /var/tmp/talos-1.9.1]# vmadm create -f 1.9.1.json
Successfully created VM 0f2dbd0c-f314-4bb7-932c-f3520b7d93d1
----

. Noting the zone ID, copy the disk image to the raw device of the empty instance:
+
----
[root@headnode (cabin) /var/tmp/talos-1.9.1]# dd if=metal-amd64.raw of=/dev/zvol/rdsk/zones/0f2dbd0c-f314-4bb7-932c-f3520b7d93d1/disk0 bs=16M
77+1 records in
77+1 records out
1306525696 bytes (1.2 GiB) transferred in 8.571684 secs (145 MiB/sec)
----
+
TIP: at this point you might boot the instance to make additional changes e.g.
configuration management or installing guest tools etc. (see also cdrom
attachment).

. Retrieve the zvol uuid for the for the instance storage:
+
----
[root@headnode (cabin) /var/tmp/talos-1.9.1]# vmadm get 0f2dbd0c-f314-4bb7-932c-f3520b7d93d1 | json -a disks | json -a zfs_filesystem
zones/0f2dbd0c-f314-4bb7-932c-f3520b7d93d1/disk0
----

. Create a snapshot of the zvol and copy it to a file (in this example the quota needed to be extended to allow the snapshot creation):
+
----
[root@headnode (cabin) /var/tmp/talos-1.9.1]# zfs get quota zones/0f2dbd0c-f314-4bb7-932c-f3520b7d93d1
NAME                                        PROPERTY  VALUE  SOURCE
zones/0f2dbd0c-f314-4bb7-932c-f3520b7d93d1  quota     30.3G  local
[root@headnode (cabin) /var/tmp/talos-1.9.1]# zfs set quota=40G zones/0f2dbd0c-f314-4bb7-932c-f3520b7d93d1
[root@headnode (cabin) /var/tmp/talos-1.9.1]# zfs snapshot zones/0f2dbd0c-f314-4bb7-932c-f3520b7d93d1/disk0@dataset
[root@headnode (cabin) /var/tmp/talos-1.9.1]# zfs send zones/0f2dbd0c-f314-4bb7-932c-f3520b7d93d1/disk0@dataset | gzip > 1.9.1.zvol.gz
[root@headnode (cabin) /var/tmp/talos-1.9.1]# ls -l 1.9.1.zvol.gz
-rw-r--r--   1 root     root     109388709 Jan  2 11:38 1.9.1.zvol.gz
----

. Create a IMGAPI manifest that describes the desired image:
+
----
{
  "v": "2",
  "uuid": "<from the output of uuid>",
  "owner": "<from the output of sdc-ldap s 'login=admin' | grep ^uuid | cut -d' ' -f2>",
  "name": "talos-1.9.1",
  "description": "Talos Linux 1.9.1 (SDC v0.0.1)",
  "version": "0.0.1",
  "state": "active",
  "disabled": false,
  "public": true,
  "os": "linux",
  "type": "zvol",
  "files": [
    {
      "sha1": "<from the output of sum -x sha1 /var/tmp/talos-1.9.1/1.9.1.zvol.gz | cut -d' ' -f1>"
      "size": <from the output of ls -l /var/tmp/talos-1.9.1/1.9.1.zvol.gz | awk '{ print $5 }'>,
      "compression": "gzip"
    }
  ],
  "requirements": {
    "networks": [
      {
        "name": "net0",
        "description": "public"
      }
    ],
   "brand": "bhyve",
   "bootrom": "uefi"
  },
  "image_size": "<as specified in disks.size in talos-1.9.1.vmdef.json>",
  "disk_driver": "virtio",
  "nic_driver": "virtio",
  "cpu_type": "host"
}
----

. Finally, import the image:
+
----
[root@headnode (cabin) /var/tmp/talos-1.9.1]# sdc-imgadm import -m /var/tmp/talos-1.9.1/1.9.1.manifest.json -f /var/tmp/talos-1.9.1/1.9.1.zvol.gz
Imported image 01699ed6-c901-11ef-b6be-7085c2dbfb7d (talos-1.9.1, 0.0.1, state=unactivated)
...c901-11ef-b6be-7085c2dbfb7d [=======================================================>] 100% 104.32MB
Added file "/var/tmp/talos-1.9.1/1.9.1.zvol.gz" (compression "gzip") to image 01699ed6-c901-11ef-b6be-7085c2dbfb7d
Activated image 01699ed6-c901-11ef-b6be-7085c2dbfb7d
----

=== Console output from bhyve instances

In order to access to the console of a bhyve instance via VNC, the instance must
be running with a UEFI bootrom rather than legacy BIOS. For public images this
is already set so happens automatically. For self-built images one must enable
it in the image https://smartdatacenter.topicbox.com/groups/sdc-discuss/Td4b1c1bb557bae11/spring-2024-hvm-images[thus]:

`sdc-imgadm update <uuid> requirements.brand=bhyve requirements.bootrom=uefi`

For instances not started/managed by Triton, the UEFI bootrom can be enabled on
a stopped instance directly via `vmadm(8)` on the given compute node:

----
vmadm stop <uuid>
vmadm update <uuid> bootrom="/usr/share/bhyve/uefi-rom.bin"
vmadm start <uuid>
----

=== Resizing bhyve instances

Resizing instances cannot be done via the console. There are however three ways
to change the CPU and memory limits for a virtual machine. All require the
instance to be in the stopped state.

. via `vmadm(8)`
. via the Triton VMAPI: `sdc sdc-vmapi /vms/<instance uuid>?action=update -d '{"billing_id":"<new package uuid>"}'`
. via the https://smartdatacenter.topicbox.com/groups/sdc-discuss/T0609521b5cfbff31-Mc983b2dc841bdb365667bf46/resize-a-bhyve-instance[triton CLI] (need to research this)


===  Triton packages/PAPI

Feature-wise PAPI is pretty thread-bare. A Triton Package is a bundling of
resources that, in conjunction with an image, define a VM. All salient aspects
of a Package are immutable, and Packages themselves can't be deleted nor
renamed, which is a bit painful. Good news is that in the Console the default
search is for _active_ packages so the churn can be hidden with some fastidious
deactivation.
* quotas in packages being less than images fails silently

=== Storage

* the two disk thing, must try to find that post
* quotas

=== migration

* works :)

== Networking

* Instances that do not have the guest agent cannot be assigned IP addresses
from the Triton DHCP server. In order to get an assignment from an external DHCP
server _Allow DHCP Spoofing_ must be enabled in the console which corresponds to
the `nics[*].allow_dhcp_spoofing` boolean in VMAPI.

* investigate IP/MAC spoofing and wireguard

== Miscellanea

* headnode console session history
* must explore https://www.npmjs.com/package/triton
* destroyed images
